org.gradle.jvmargs=-Xmx2G

# Mod Info
maven_group = io.github.shulej
archives_base_name = createsifter
mod_version = V1

minecraft_version = 1.20.1

# Dependencies
# https://fabricmc.net/develop
fabric_loader_version = 0.17.2
fabric_api_version = 0.92.11+1.20.1

# Mappings
# https://parchmentmc.org/docs/getting-started
parchment_version = 2023.09.03

# Create
# Local Create Fabric 6.0.8.1 jar (libs/create-fabric-6.0.8.1.jar)
create_version = 6.0.8.1+build.1744-mc1.20.1

# Development QOL
# Create supports all 3 recipe viewers: JEI, REI, and EMI. This decides which is enabled at runtime.
# set to 'disabled' to have none of them.
recipe_viewer = jei
# JEI - https://www.curseforge.com/minecraft/mc-mods/jei/files/all
jei_version = 15.49.0.191
# REI - https://modrinth.com/mod/rei/versions
rei_version = 12.0.626
# EMI - https://modrinth.com/mod/emi/versions
emi_version = 1.0.9+1.20.1

# Mod Menu - https://modrinth.com/mod/modmenu/versions
modmenu_version = 7.2.2


